export const foo = '';

export const PARTICIPANT_ACTIONS = {
  LOAD_PARTICIPANTS: 'PARTICIPANT_LOAD_PARTICIPANTS',
  LOAD_PARTICIPANT: 'PARTICIPANT_LOAD_PARTICIPANT',
  LOAD_STANDING: 'PARTICIPANT_LOAD_STANDING',
  LOAD_TOTAL_BETS: 'PARTICIPANT_LOAD_TOTAL_BETS',
};
