export const bar = '';

export const PARTICIPANT_MUTATIONS = {
  CLEAR: 'PARTICIPANT_CLEAR',
  SET_PARTICIPANTS: 'PARTICIPANT_SET_PARTICIPANTS',
  SET_PARTICIPANTS_LOADING: 'PARTICIPANT_SET_PARTICIPANTS_LOADING',
  SET_PARTICIPANT: 'PARTICIPANT_SET_PARTICIPANT',
  SET_PARTICIPANT_LOADING: 'PARTICIPANT_SET_PARTICIPANT_LOADING',
  SET_STANDING: 'PARTICIPANT_SET_STANDING',
  SET_STANDING_LOADING: 'PARTICIPANT_SET_STANDING_LOADING',
  SET_TOTAL_BETS: 'PARTICIPANT_SET_TOTAL_BETS',
  SET_TOTAL_BETS_LOADING: 'PARTICIPANT_SET_TOTAL_BETS_LOADING',
};
