export const bar = '';

export const PARTICIPANT_MUTATIONS = {
  CLEAR: 'PARTICIPANT_CLEAR',
  SET_PARTICIPANTS: 'PARTICIPANT_SET_PARTICIPANTS',
  SET_PARTICIPANTS_LOADING: 'PARTICIPANT_SET_PARTICIPANTS_LOADING',
  SET_PARTICIPANT: 'PARTICIPANT_SET_PARTICIPANT',
  SET_PARTICIPANT_LOADING: 'PARTICIPANT_SET_PARTICIPANT_LOADING',
};
